/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hp.View.JIF;

import com.hp.Dao.GoodsIMPL;
import com.hp.Dao.IGoods;
import com.hp.Dao.ISupplier;
import com.hp.Dao.SupplierIMPL;
import com.hp.Po.Goods;
import com.hp.Util.StringUtile;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dr.Thri
 */ 
public class ClientStuffManagement extends javax.swing.JInternalFrame {
     IGoods ig=new GoodsIMPL();
     ISupplier isu=new SupplierIMPL();
    /**
     * Creates new form Client_Stuff_Manage
     */
    public ClientStuffManagement() {
        initComponents();
        this.btndelete.setEnabled(false);
        this.btnupdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblgoods = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtsafenum = new javax.swing.JTextField();
        txtbuymoney = new javax.swing.JTextField();
        txtsalemoney = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnf5 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtGoodstype = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtOwnerId = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnum = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("商品管理");

        tblgoods.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "编号", "产品名称", "产品型号", "安全存量", "建议购买价", "建议零售价", "当前数量", "最后进货日期", "最后送货时间"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblgoods.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblgoodsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblgoods);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("手工编号：");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("安全存量：");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("产品名称：");

        jLabel4.setText("建议购买价：");

        jLabel5.setText("建议销售价：");

        btnadd.setText("新增");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnf5.setText("更新");
        btnf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf5ActionPerformed(evt);
            }
        });

        btnupdate.setText("修改");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btncancel.setText("取消");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btndelete.setText("删除");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnexit.setText("退出");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("红色文本为必填项！");

        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("商品型号：");

        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("供应商ID：");

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("当前数量：");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(364, 364, 364)
                                .addComponent(btnadd)
                                .addGap(18, 18, 18)
                                .addComponent(btnf5)
                                .addGap(18, 18, 18)
                                .addComponent(btnupdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btncancel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btndelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnexit))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtsafenum, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtsid))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtOwnerId, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(134, 134, 134)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel4)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel5)
                                                    .addGap(122, 122, 122))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addComponent(jLabel3)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(118, 118, 118)
                                                    .addComponent(jLabel7)
                                                    .addGap(21, 21, 21)
                                                    .addComponent(txtGoodstype, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(223, 223, 223)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtnum, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                            .addComponent(txtbuymoney))
                                        .addGap(213, 213, 213)
                                        .addComponent(txtsalemoney, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtGoodstype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(txtsafenum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbuymoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsalemoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtOwnerId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd)
                            .addComponent(btnf5)
                            .addComponent(btnupdate)
                            .addComponent(btncancel)
                            .addComponent(btndelete)
                            .addComponent(btnexit))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
         String sid = this.txtsid.getText().trim();
        String name = this.txtname.getText().trim();
        String type=this.txtGoodstype.getText().trim();
        String num = this.txtsafenum.getText().trim();
        String bnum = this.txtbuymoney.getText().trim();
        String snum = this.txtsalemoney.getText().trim();
        String Oid=this.txtOwnerId.getText().trim();
        String pnum=this.txtnum.getText().trim();
        if(StringUtile.validateNull(sid) == false){
            JOptionPane.showMessageDialog(this,"手工编号不能为空");
            return;
        }
        if(StringUtile.validateNull(name) == false){
            JOptionPane.showMessageDialog(this,"供应商简称不能为空");
            return;
        }
        if(StringUtile.validateNull(type) == false){
            JOptionPane.showMessageDialog(this,"商品型号不能为空");
            return;
        }
        if(StringUtile.validateNull(pnum) == false){
            JOptionPane.showMessageDialog(this,"商品型号不能为空");
            return;
        }
        if(StringUtile.validateNull(Oid) == false){
            JOptionPane.showMessageDialog(this,"供应商ID不能为空");
            return;
        }
         if(StringUtile.validateDigit(Oid) == false){
            JOptionPane.showMessageDialog(this, "供应商ID必须为数字");
            return;
        }
          if(StringUtile.validateDigit(pnum) == false){
            JOptionPane.showMessageDialog(this, "当前数量必须为数字");
            return;
        }
          if(StringUtile.validateDigit(num) == false){
            JOptionPane.showMessageDialog(this, "安全存量须为数字");
            return;
        }
          if(StringUtile.validateDigit(snum) == false){
            JOptionPane.showMessageDialog(this, "建议销售价格必须为数字");
            return;
        }
           if(StringUtile.validateDigit(bnum) == false){
            JOptionPane.showMessageDialog(this, "建议购买价格必须为数字");
            return;
        }
          int oid=Integer.valueOf(Oid);
          
          if(!isu.Thri_findBySupplierId(oid)){
           JOptionPane.showMessageDialog(this, "添加失败，供应商不存在");return;
          }
        Goods s = new Goods(sid,name,type,num,bnum,snum,pnum,oid);
        if(ig.Thri_findByGoods(s)){
            JOptionPane.showMessageDialog(this, "添加失败，商品已存在");
            btncancelActionPerformed(evt);
            return;
        
        }
        
        int result = ig.Thri_addGoods(s);
         
          if(result != 0 ){
            JOptionPane.showMessageDialog(this, "添加成功");
            btnf5ActionPerformed( evt);
            btncancelActionPerformed(evt);
          }else{
              JOptionPane.showMessageDialog(this, "添加失败");
          }
        
    }//GEN-LAST:event_btnaddActionPerformed

    private void btnf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5ActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
         List<Goods> list =ig.Thri_getGoods();
        // 获取表格中的行进行删除
        DefaultTableModel dtm =(DefaultTableModel) this.tblgoods.getModel();
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        for(Goods g :list){
            Vector v = new Vector();
            v.add(g.getDefineId());
            v.add(g.getGoodsName());
            v.add(g.getGoodsType());
            v.add(g.getSafeNum());
            v.add(g.getAdviceBuyPrice());
            v.add(g.getAdviceSalePrice());
            v.add(g.getPresentNumber());
            v.add(g.getInTime());
            v.add(g.getOutTime());
            dtm.addRow(v);
        }
    }//GEN-LAST:event_btnf5ActionPerformed

    private void tblgoodsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblgoodsMouseClicked
        // TODO add your handling code here:
       this.txtsid.setEnabled(false);
       this.txtname.setEnabled(false);
       this.txtOwnerId.setEnabled(false);
       int selectRow =  this.tblgoods.getSelectedRow();
       txtsid.setText((String)this.tblgoods.getValueAt(selectRow,0));
       txtname.setText((String)this.tblgoods.getValueAt(selectRow, 1));
       txtGoodstype.setText((String)this.tblgoods.getValueAt(selectRow,2));
       txtsafenum.setText((String)this.tblgoods.getValueAt(selectRow,3));
       txtbuymoney.setText((String)this.tblgoods.getValueAt(selectRow,4));
       txtsalemoney.setText((String)this.tblgoods.getValueAt(selectRow,5));
       txtnum.setText((String)this.tblgoods.getValueAt(selectRow,6));
      
       this.btnadd.setEnabled(false);
       this.btnupdate.setEnabled(true);
       this.btndelete.setEnabled(true);
    }//GEN-LAST:event_tblgoodsMouseClicked

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
     this.txtsid.setText("");
     this.txtname.setText("");
     this.txtsafenum.setText("");
     this.txtbuymoney.setText("");
     this.txtsalemoney.setText("");
     this.txtnum.setText("");
     this.txtGoodstype.setText("");
     this.txtOwnerId.setText("");
      this.txtsid.setEnabled(true);
       this.txtname.setEnabled(true);
       this.txtOwnerId.setEnabled(true);
     this.btnadd.setEnabled(true);//启用添加按钮
     this.btndelete.setEnabled(false);//禁用删除
     this.btnupdate.setEnabled(false);//禁用修改
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:       
        String name = this.txtname.getText().trim();
        String type=this.txtGoodstype.getText().trim();
        String num = this.txtsafenum.getText().trim();
        String bnum = this.txtbuymoney.getText().trim();
        String snum = this.txtsalemoney.getText().trim();
        String pnum=this.txtnum.getText().trim();
        
        if(StringUtile.validateNull(type) == false){
            JOptionPane.showMessageDialog(this,"商品型号不能为空");
            return;
        }
        if(StringUtile.validateNull(pnum) == false){
            JOptionPane.showMessageDialog(this,"商品型号不能为空");
            return;
        }
       
          if(StringUtile.validateDigit(pnum) == false){
            JOptionPane.showMessageDialog(this, "当前数量必须为数字");
            return;
        }
          if(StringUtile.validateDigit(num) == false){
            JOptionPane.showMessageDialog(this, "安全存量须为数字");
            return;
        }
          if(StringUtile.validateDigit(snum) == false){
            JOptionPane.showMessageDialog(this, "建议销售价格必须为数字");
            return;
        }
           if(StringUtile.validateDigit(bnum) == false){
            JOptionPane.showMessageDialog(this, "建议购买价格必须为数字");
            return;
        }
        
        Goods g = new Goods(name,type,num,bnum,snum,pnum);
        
        int result = ig.Thri_updateGoods(g);
         
          if(result != 0 ){
              JOptionPane.showMessageDialog(this, "修改成功");
            btnf5ActionPerformed( evt);
            btncancelActionPerformed(evt);
          }else{
              JOptionPane.showMessageDialog(this, "修改失败");
          }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         String name = this.txtname.getText();
        
        int result = ig.Thri_deletegoods(name);
        if(result >0){
            JOptionPane.showMessageDialog(this, "删除成功");
             btnf5ActionPerformed( evt);
            btncancelActionPerformed(evt); 
        }else{
            JOptionPane.showMessageDialog(this, "删除失败");
        }
    }//GEN-LAST:event_btndeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnf5;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblgoods;
    private javax.swing.JTextField txtGoodstype;
    private javax.swing.JTextField txtOwnerId;
    private javax.swing.JTextField txtbuymoney;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtnum;
    private javax.swing.JTextField txtsafenum;
    private javax.swing.JTextField txtsalemoney;
    private javax.swing.JTextField txtsid;
    // End of variables declaration//GEN-END:variables
}
