/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hp.View.JIF;

import com.hp.Dao.ClientIMPL;
import com.hp.Dao.IClient;
import com.hp.Po.Client;
import com.hp.Util.StringUtile;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muggle
 */
public class CustomerManagement extends javax.swing.JInternalFrame {
    IClient ict =new ClientIMPL();
    /**
     * Creates new form CustomerManagement
     */
    public CustomerManagement() {
        initComponents();
        this.btnDelete.setEnabled(false);
        this.btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClient = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtClientId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtClientName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTaoBaoId = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMobilePhone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPost = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtDeliveryAddress = new javax.swing.JTextField();
        btnQuit = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("客户管理");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblClient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "客户编号", "客户姓名", "淘宝号", "电话", "移动电话", "送货地址", "邮编", "最近送货日期"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClient.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClient);
        if (tblClient.getColumnModel().getColumnCount() > 0) {
            tblClient.getColumnModel().getColumn(0).setResizable(false);
            tblClient.getColumnModel().getColumn(1).setResizable(false);
            tblClient.getColumnModel().getColumn(2).setResizable(false);
            tblClient.getColumnModel().getColumn(3).setResizable(false);
            tblClient.getColumnModel().getColumn(4).setResizable(false);
            tblClient.getColumnModel().getColumn(5).setResizable(false);
            tblClient.getColumnModel().getColumn(6).setResizable(false);
            tblClient.getColumnModel().getColumn(7).setResizable(false);
        }

        jLabel1.setText("客户编号:");

        jLabel2.setText("客户姓名:");

        jLabel3.setText("淘宝号:");

        jLabel4.setText("电话:");

        jLabel5.setText("移动电话:");

        jLabel6.setText("邮编:");

        jLabel7.setText("送货地址:");

        btnQuit.setText("退出");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("修改");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("重置");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTaoBaoId, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(64, 64, 64)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDeliveryAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReset)
                        .addGap(33, 33, 33)
                        .addComponent(btnQuit)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtClientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtTaoBaoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtMobilePhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(txtPost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtDeliveryAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuit)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnReset))
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String str = this.txtSearch.getText();
        List<Client> list = ict.getClient(str);
        DefaultTableModel dtm = (DefaultTableModel) this.tblClient.getModel();
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        for(Client c : list){
            Vector v = new Vector();
            v.add(c.getClientId());
            v.add(c.getClientName());
            v.add(c.getTaobaoId());
            v.add(c.getPhone());
            v.add(c.getMobilePhone());
            v.add(c.getDeliveryAddress());
            v.add(c.getPost());
            v.add(c.getBuyTime());
            dtm.addRow(v);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String clientid = this.txtClientId.getText().trim();
        String clientname = this.txtClientName.getText().trim();
        String taobaoid = this.txtTaoBaoId.getText().trim();
        String phone = this.txtPhone.getText().trim();
        String mobilephone = this.txtMobilePhone.getText().trim();
        String post = this.txtPost.getText().trim();
        String deliveryaddress = this.txtDeliveryAddress.getText().trim(); 
        if(StringUtile.validateNull(clientid) == false){
            JOptionPane.showMessageDialog(this, "客户编号不能为空");
            return;
        }
        if(StringUtile.validateNull(clientname) == false){
            JOptionPane.showMessageDialog(this, "客户姓名不能为空");
            return;
        }
        if(StringUtile.validateNull(taobaoid) == false){
            JOptionPane.showMessageDialog(this, "淘宝号不能为空");
            return;
        }
         if(StringUtile.validateDigit(phone) == false){
            JOptionPane.showMessageDialog(this, "电话必须为数字");
            return;
        }
        if(StringUtile.validateDigit(mobilephone) == false){
            JOptionPane.showMessageDialog(this, "移动电话必须是数字");
            return;
        }
        if(StringUtile.validateDigit(post) == false){
            JOptionPane.showMessageDialog(this, "邮编必须为数字");
            return;
        }
        if(StringUtile.validateNull(deliveryaddress) == false){
            JOptionPane.showMessageDialog(this, "送货地址不能为空");
            return;
        }
        Client c = new Client(clientid,clientname,taobaoid,phone,mobilephone,deliveryaddress,post);
        if(ict.findByClient(c)){
            JOptionPane.showMessageDialog(this, "客户资料已存在");
            btnResetActionPerformed( evt);
            return;
        }
        int result = ict.addClient(c);
        if(result != 0){
            JOptionPane.showMessageDialog(this, "添加成功");
            btnSearchActionPerformed( evt);
            btnResetActionPerformed( evt);
        }else{
            JOptionPane.showMessageDialog(this, "添加失败");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.txtClientId.setText("");
        this.txtClientName.setText("");
        this.txtTaoBaoId.setText("");
        this.txtPhone.setText("");
        this.txtMobilePhone.setText("");
        this.txtDeliveryAddress.setText("");
        this.txtPost.setText("");
        this.btnAdd.setEnabled(true);
        this.btnDelete.setEnabled(false);
        this.btnUpdate.setEnabled(false);
        this.txtClientId.setEnabled(true);
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblClientMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientMouseClicked
        // TODO add your handling code here:
        this.txtClientId.setEnabled(false);
        int selectRow = this.tblClient.getSelectedRow();
        this.txtClientId.setText((String) this.tblClient.getValueAt(selectRow, 0));
        this.txtClientName.setText((String) this.tblClient.getValueAt(selectRow, 1));
        this.txtTaoBaoId.setText((String) this.tblClient.getValueAt(selectRow, 2));
        this.txtPhone.setText((String) this.tblClient.getValueAt(selectRow, 3));
        this.txtMobilePhone.setText((String) this.tblClient.getValueAt(selectRow, 4));
        this.txtDeliveryAddress.setText((String) this.tblClient.getValueAt(selectRow, 5));
        this.txtPost.setText((String) this.tblClient.getValueAt(selectRow, 6));
        this.btnAdd.setEnabled(false);
        this.btnDelete.setEnabled(true);
        this.btnUpdate.setEnabled(true);
    }//GEN-LAST:event_tblClientMouseClicked

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) this.tblClient.getModel();
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        btnResetActionPerformed(evt);
        setVisible(false);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String clientid = this.txtClientId.getText().trim();
        String clientname = this.txtClientName.getText().trim();
        String taobaoid = this.txtTaoBaoId.getText().trim();
        String phone = this.txtPhone.getText().trim();
        String mobilephone = this.txtMobilePhone.getText().trim();
        String post = this.txtPost.getText().trim();
        String deliveryaddress = this.txtDeliveryAddress.getText().trim(); 
        if(StringUtile.validateNull(clientid) == false){
            JOptionPane.showMessageDialog(this, "客户编号不能为空");
            return;
        }
        if(StringUtile.validateNull(clientname) == false){
            JOptionPane.showMessageDialog(this, "客户姓名不能为空");
            return;
        }
        if(StringUtile.validateNull(taobaoid) == false){
            JOptionPane.showMessageDialog(this, "淘宝号不能为空");
            return;
        }
         if(StringUtile.validateDigit(phone) == false){
            JOptionPane.showMessageDialog(this, "电话必须为数字");
            return;
        }
        if(StringUtile.validateDigit(mobilephone) == false){
            JOptionPane.showMessageDialog(this, "移动电话必须是数字");
            return;
        }
        if(StringUtile.validateDigit(post) == false){
            JOptionPane.showMessageDialog(this, "邮编必须为数字");
            return;
        }
        if(StringUtile.validateNull(deliveryaddress) == false){
            JOptionPane.showMessageDialog(this, "送货地址不能为空");
            return;
        }
        Client c = new Client(clientid,clientname,taobaoid,phone,mobilephone,deliveryaddress,post);
        int result = ict.updateClient(c);
        if(result > 0){
            JOptionPane.showMessageDialog(this, "修改成功");
            btnSearchActionPerformed( evt);
            btnResetActionPerformed( evt);
        }else{
            JOptionPane.showMessageDialog(this, "修改失败");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String clientid = this.txtClientId.getText().trim();
        int result = ict.deleteClient(clientid);
        if(result > 0){
            JOptionPane.showMessageDialog(this, "删除成功");
            btnSearchActionPerformed( evt);
            btnResetActionPerformed( evt);
        }else{
            JOptionPane.showMessageDialog(this, "删除失败");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClient;
    private javax.swing.JTextField txtClientId;
    private javax.swing.JTextField txtClientName;
    private javax.swing.JTextField txtDeliveryAddress;
    private javax.swing.JTextField txtMobilePhone;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPost;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTaoBaoId;
    // End of variables declaration//GEN-END:variables
}
