/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hp.View.JIF;

import com.hp.Dao.IStaff;
import com.hp.Dao.StaffIMPL;
import com.hp.Po.Staff;
import com.hp.Util.StringUtile;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Muggle
 */
public class EmployeeManagement extends javax.swing.JInternalFrame {
    IStaff isf = new StaffIMPL();
    /**
     * Creates new form EmployeeManagement
     */
    public EmployeeManagement() {
        initComponents();
        this.btnDelete.setEnabled(false);
        this.btnUpdate.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStaff = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtStaffid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtStaffname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxSex = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNativeplace = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPresentaddress = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtQq = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtWechat = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        txtWorktype = new javax.swing.JComboBox<>();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("员工管理");

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblStaff.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "员工编号", "员工姓名", "性别", "籍贯", "现住址", "电话", "QQ", "微信", "工作性质"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStaffMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblStaff);
        if (tblStaff.getColumnModel().getColumnCount() > 0) {
            tblStaff.getColumnModel().getColumn(0).setResizable(false);
            tblStaff.getColumnModel().getColumn(1).setResizable(false);
            tblStaff.getColumnModel().getColumn(2).setResizable(false);
            tblStaff.getColumnModel().getColumn(3).setResizable(false);
            tblStaff.getColumnModel().getColumn(4).setResizable(false);
            tblStaff.getColumnModel().getColumn(5).setResizable(false);
            tblStaff.getColumnModel().getColumn(6).setResizable(false);
            tblStaff.getColumnModel().getColumn(7).setResizable(false);
            tblStaff.getColumnModel().getColumn(8).setResizable(false);
        }

        jLabel1.setText("员工编号:");

        jLabel2.setText("员工姓名:");

        jLabel3.setText("性别:");

        cbxSex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "男", "女" }));

        jLabel4.setText("籍贯:");

        jLabel5.setText("现住址:");

        jLabel6.setText("电话:");

        jLabel7.setText("QQ:");

        jLabel8.setText("微信:");

        jLabel9.setText("工作性质:");

        btnAdd.setText("新增");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setText("修改");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("删除");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReset.setText("重置");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnQuit.setText("退出");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        txtWorktype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "超级管理员", "员工", "销售员" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtStaffid, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtStaffname, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtPresentaddress))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxSex, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAdd)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnUpdate)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDelete)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnReset)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                        .addComponent(btnQuit))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNativeplace))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtQq))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtWechat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtWorktype, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(452, 452, 452)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStaffid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtStaffname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbxSex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNativeplace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtPresentaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtQq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtWechat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtWorktype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnReset)
                    .addComponent(btnQuit))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String str = this.txtSearch.getText();
        List<Staff> list = isf.getStaff(str);
        DefaultTableModel dtm = (DefaultTableModel) this.tblStaff.getModel();
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        for(Staff s : list){
            Vector v = new Vector();
            v.add(s.getStaffId());
            v.add(s.getStaffName());
            v.add(s.getSex());
            v.add(s.getNativePlace());
            v.add(s.getPresentAddress());
            v.add(s.getPhone());
            v.add(s.getQQ());
            v.add(s.getWeChat());
            v.add(s.getWorkType());
            dtm.addRow(v);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String staffid = this.txtStaffid.getText().trim();
        String staffname = this.txtStaffname.getText().trim();
        String sex = this.cbxSex.getSelectedItem().toString().trim();
        String nativeplace = this.txtNativeplace.getText().trim();
        String presentaddress = this.txtPresentaddress.getText().trim();
        String phone = this.txtPhone.getText().trim();
        String qq = this.txtQq.getText().trim();
        String wechat = this.txtWechat.getText().trim();
        String worktype = (String)this.txtWorktype.getSelectedItem();
        if(StringUtile.validateNull(staffid) == false){
            JOptionPane.showMessageDialog(this, "员工编号不能为空");
            return;
        }
        if(StringUtile.validateNull(staffname) == false){
            JOptionPane.showMessageDialog(this, "员工姓名不能为空");
            return;
        }
        if(StringUtile.validateNull(nativeplace) == false){
            JOptionPane.showMessageDialog(this, "籍贯不能为空");
            return;
        }
        if(StringUtile.validateNull(presentaddress) == false){
            JOptionPane.showMessageDialog(this, "现住址不能为空");
            return;
        }
        if(StringUtile.validateDigit(phone) == false){
            JOptionPane.showMessageDialog(this, "电话必须为数字");
            return;
        }
        if(StringUtile.validateDigit(qq) == false){
            JOptionPane.showMessageDialog(this, "QQ必须为数字");
            return;
        }
        if(StringUtile.validateNull(wechat) == false){
            JOptionPane.showMessageDialog(this, "微信不能为空");
            return;
        }
        if(StringUtile.validateNull(worktype) == false){
            JOptionPane.showMessageDialog(this, "工作性质不能为空");
            return;
        }
        Staff s = new Staff(staffid,staffname,sex,nativeplace,presentaddress,phone,qq,wechat,worktype);
        if(isf.findByStaff(s)){
            JOptionPane.showMessageDialog(this, "员工已存在");
            btnResetActionPerformed( evt);
            return;
        }
        int result = isf.addStaff(s);
        if(result != 0){
            JOptionPane.showMessageDialog(this, "添加成功");
            btnResetActionPerformed( evt);
            btnSearchActionPerformed( evt);
        }else{
            JOptionPane.showMessageDialog(this, "添加失败");
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        this.txtStaffid.setText("");
        this.txtStaffname.setText("");
        this.cbxSex.setSelectedItem(" ");
        this.txtNativeplace.setText("");
        this.txtPresentaddress.setText("");
        this.txtPhone.setText("");
        this.txtQq.setText("");
        this.txtWechat.setText("");
        this.txtWorktype.setSelectedItem("");
        this.btnAdd.setEnabled(true);
        this.btnDelete.setEnabled(false);
        this.btnUpdate.setEnabled(false);
        this.txtStaffid.setEnabled(true);
        
    }//GEN-LAST:event_btnResetActionPerformed

    private void tblStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffMouseClicked
        // TODO add your handling code here:
        this.txtStaffid.setEnabled(false);
        int selectRow = this.tblStaff.getSelectedRow();
        this.txtStaffid.setText((String) this.tblStaff.getValueAt(selectRow, 0));
        this.txtStaffname.setText((String) this.tblStaff.getValueAt(selectRow, 1));
        this.cbxSex.setSelectedItem(this.tblStaff.getValueAt(selectRow, 2));
        this.txtNativeplace.setText((String) this.tblStaff.getValueAt(selectRow, 3));
        this.txtPresentaddress.setText((String) this.tblStaff.getValueAt(selectRow, 4));
        this.txtPhone.setText((String) this.tblStaff.getValueAt(selectRow, 5));
        this.txtQq.setText((String) this.tblStaff.getValueAt(selectRow, 6));
        this.txtWechat.setText((String) this.tblStaff.getValueAt(selectRow, 7));
        this.txtWorktype.setSelectedItem(this.tblStaff.getValueAt(selectRow, 8));
        this.btnAdd.setEnabled(false);
        this.btnDelete.setEnabled(true);
        this.btnUpdate.setEnabled(true);
    }//GEN-LAST:event_tblStaffMouseClicked

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        String staffid = this.txtStaffid.getText().trim();
        String staffname = this.txtStaffname.getText().trim();
        String sex = this.cbxSex.getSelectedItem().toString().trim();
        String nativeplace = this.txtNativeplace.getText().trim();
        String presentaddress = this.txtPresentaddress.getText().trim();
        String phone = this.txtPhone.getText().trim();
        String qq = this.txtQq.getText().trim();
        String wechat = this.txtWechat.getText().trim();
        String worktype =this.txtWorktype.getSelectedItem().toString().trim();
        if(StringUtile.validateNull(staffid) == false){
            JOptionPane.showMessageDialog(this, "员工编号不能为空");
            return;
        }
        if(StringUtile.validateNull(staffname) == false){
            JOptionPane.showMessageDialog(this, "员工姓名不能为空");
            return;
        }
        if(StringUtile.validateNull(nativeplace) == false){
            JOptionPane.showMessageDialog(this, "籍贯不能为空");
            return;
        }
        if(StringUtile.validateNull(presentaddress) == false){
            JOptionPane.showMessageDialog(this, "现住址不能为空");
            return;
        }
        if(StringUtile.validateDigit(phone) == false){
            JOptionPane.showMessageDialog(this, "电话必须为数字");
            return;
        }
        if(StringUtile.validateDigit(qq) == false){
            JOptionPane.showMessageDialog(this, "QQ必须为数字");
            return;
        }
        if(StringUtile.validateNull(wechat) == false){
            JOptionPane.showMessageDialog(this, "微信不能为空");
            return;
        }
        if(StringUtile.validateNull(worktype) == false){
            JOptionPane.showMessageDialog(this, "工作性质不能为空");
            return;
        }
        Staff s = new Staff(staffid,staffname,sex,nativeplace,presentaddress,phone,qq,wechat,worktype);
        int result = isf.updateStaff(s);
        if(result != 0){
            JOptionPane.showMessageDialog(this, "修改成功");
            btnResetActionPerformed( evt);
            btnSearchActionPerformed( evt);
        }else{
            JOptionPane.showMessageDialog(this, "修改失败");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String sid = this.txtStaffid.getText().trim();
        String staffName  = this.txtStaffname.getText().trim();
        int result = isf.deleteStaff(sid,staffName);
         if(result > 0){
            JOptionPane.showMessageDialog(this, "删除成功");
            btnSearchActionPerformed( evt);
            btnResetActionPerformed( evt);
        }else{
            JOptionPane.showMessageDialog(this, "删除失败");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbxSex;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblStaff;
    private javax.swing.JTextField txtNativeplace;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPresentaddress;
    private javax.swing.JTextField txtQq;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtStaffid;
    private javax.swing.JTextField txtStaffname;
    private javax.swing.JTextField txtWechat;
    private javax.swing.JComboBox<String> txtWorktype;
    // End of variables declaration//GEN-END:variables
}
