/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hp.View.JIF;

import com.hp.Dao.ISaleBill;
import com.hp.Dao.SaleBillIMPL;
import com.hp.Po.SaleBill;
import java.sql.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dr.Thri
 */
public class SaleReturn extends javax.swing.JInternalFrame {
    ISaleBill ipd = new SaleBillIMPL();
    /**
     * Creates new form SaleReturn
     */
    public SaleReturn() {
        initComponents();
        this.getRootPane().setDefaultButton(btnSearch);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        SaleId = new javax.swing.JLabel();
        GoodsId = new javax.swing.JLabel();
        SaleNumber = new javax.swing.JLabel();
        ReturnNumber = new javax.swing.JLabel();
        btnReaturnNumber = new javax.swing.JButton();
        txtSaleId = new javax.swing.JTextField();
        txtGoodsId = new javax.swing.JTextField();
        txtSaleNumber = new javax.swing.JTextField();
        txtReaturnNumber = new javax.swing.JTextField();
        btnStartTime = new com.hp.Util.DateChooserJButton();
        btnFinshTime = new com.hp.Util.DateChooserJButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("销售退货");

        jLabel1.setText("-");

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "销售编号", "商品编号", "商品名称", "销售数量", "销售价格", "客户编号", "客户名称", "销售时间"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProductMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(0).setResizable(false);
            tblProduct.getColumnModel().getColumn(1).setResizable(false);
            tblProduct.getColumnModel().getColumn(2).setResizable(false);
            tblProduct.getColumnModel().getColumn(3).setResizable(false);
            tblProduct.getColumnModel().getColumn(4).setResizable(false);
            tblProduct.getColumnModel().getColumn(5).setResizable(false);
            tblProduct.getColumnModel().getColumn(6).setResizable(false);
            tblProduct.getColumnModel().getColumn(7).setResizable(false);
        }

        SaleId.setText("销售编号：");

        GoodsId.setText("商品编号：");

        SaleNumber.setText("销售数量：");

        ReturnNumber.setText("退货数量：");

        btnReaturnNumber.setText("销售退货");
        btnReaturnNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReaturnNumberActionPerformed(evt);
            }
        });

        txtSaleId.setEnabled(false);

        txtGoodsId.setEnabled(false);

        txtSaleNumber.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnFinshTime, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ReturnNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtReaturnNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SaleId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSaleId, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(GoodsId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReaturnNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                    .addComponent(txtGoodsId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SaleNumber)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSaleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(btnStartTime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFinshTime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaleId)
                    .addComponent(GoodsId)
                    .addComponent(SaleNumber)
                    .addComponent(txtSaleId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGoodsId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSaleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ReturnNumber)
                    .addComponent(btnReaturnNumber)
                    .addComponent(txtReaturnNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(94, 94, 94))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProductMouseClicked
        // TODO add your handling code here:
        int selectRow = this.tblProduct.getSelectedRow();//获取行
        this.txtSaleId.setText((String)this.tblProduct.getValueAt(selectRow,0));
        this.txtGoodsId.setText((String)this.tblProduct.getValueAt(selectRow, 1));
        
        this.txtSaleNumber.setText((String)this.tblProduct.getValueAt(selectRow, 3));
        
        
    }//GEN-LAST:event_tblProductMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         //获取输入框的数据
        String str = this.txtSearch.getText();
        //调用dao层 将我们获取到的输入框的数据作为参数传给dao
         List<SaleBill> list =ipd.getSaleBill(str);
         // 获取表格中的行进行删除
        DefaultTableModel dtm =(DefaultTableModel) this.tblProduct.getModel();
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);  
        
        }
        for(SaleBill p :list){
            Vector v = new Vector();
            v.add(p.getSaleId());
            v.add(p.getGoodsId());
            v.add(p.getGoodsName());
            v.add(p.getSaleNumber());
            v.add(p.getSalePrice());
            v.add(p.getClientId());
            v.add(p.getClientName());
            v.add(p.getSaleTime());
            
            Date date1=p.getSaleTime();
            Date date2=   new java.sql.Date(btnStartTime.getDate().getTime());//相等则返回0，date1大返回1，否则返回-1
        
            Date date3=   new java.sql.Date(btnFinshTime.getDate().getTime());
            
            if(date1.compareTo(date2)>=0&&date3.compareTo(date1)>=0)

                

        
            dtm.addRow(v);
            
        }
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnReaturnNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReaturnNumberActionPerformed
        // TODO add your handling code here:
        
        String SaleId = this.txtSaleId.getText().trim();//.trim() 消除前后空格 防止空格的输入
        String SaleNumber = this.txtSaleNumber.getText().trim();
        String ReaturnNumber = this.txtReaturnNumber.getText().trim();
        String GoodsId = this.txtGoodsId.getText().trim();
       System.out.println("GoodsId="+GoodsId);
        int result = ipd.Reaturn(SaleId,SaleNumber,ReaturnNumber);
        if(result > 0 ){
            JOptionPane.showMessageDialog(this, "退货成功,给好评喔");
            btnSearchActionPerformed( evt);
            this.txtSaleId.setText("");
            this.txtGoodsId.setText("");
            this.txtSaleNumber.setText("");
            this.txtReaturnNumber.setText("");
            int presentNum = ipd.addGoodPresentNum(ReaturnNumber,GoodsId);
        }
        else if(result==-1)
        {
             JOptionPane.showMessageDialog(this, "退货数量大于销售数量,退货失败");
        }
        else{
            JOptionPane.showMessageDialog(this, "退货失败");
            this.txtSaleId.setText("");
            this.txtGoodsId.setText("");
            this.txtSaleNumber.setText("");
            this.txtReaturnNumber.setText("");
        }
    }//GEN-LAST:event_btnReaturnNumberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GoodsId;
    private javax.swing.JLabel ReturnNumber;
    private javax.swing.JLabel SaleId;
    private javax.swing.JLabel SaleNumber;
    private com.hp.Util.DateChooserJButton btnFinshTime;
    private javax.swing.JButton btnReaturnNumber;
    private javax.swing.JButton btnSearch;
    private com.hp.Util.DateChooserJButton btnStartTime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtGoodsId;
    private javax.swing.JTextField txtReaturnNumber;
    private javax.swing.JTextField txtSaleId;
    private javax.swing.JTextField txtSaleNumber;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
