/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hp.View.JIF;

import com.hp.Dao.ISupplier;
import com.hp.Dao.SupplierIMPL;
import com.hp.Po.Supplier;
import com.hp.Util.StringUtile;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dr.Thri
 */
public class SupplyManagement extends javax.swing.JInternalFrame {
    ISupplier isp=new SupplierIMPL();
    /**
     * Creates new form SupplyManager
     */
    public SupplyManagement() {
        initComponents();
        this.btndelete.setEnabled(false);
        this.btnupdate.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSupplier = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtsid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtsname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtagent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcom_address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtphone = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMphone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtfax = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtFaddress = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jcbappliction = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnf5 = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("供应商管理");

        tblSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "供应商编号", "供应商简称", "供应商全称", "负责人", "称谓", "电话", "移动电话", "传真", "公司地址", "工厂地址"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSupplierMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSupplier);

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("供应商编号：");

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("供应商简称：");

        jLabel3.setText("供应商全称：");

        jLabel4.setText("负责人：");

        jLabel5.setText("公司地址：");

        jLabel6.setText("电话：");

        jLabel7.setText("移动电话：");

        jLabel8.setText("传真：");

        jLabel9.setText("工厂地址：");

        jLabel10.setText("称谓：");

        jcbappliction.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "员工", "总裁", "经理" }));

        jLabel11.setForeground(new java.awt.Color(255, 0, 0));
        jLabel11.setText("注意：红色字体为必填项");

        btnadd.setText("新增");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnf5.setText("更新");
        btnf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnf5ActionPerformed(evt);
            }
        });

        btnupdate.setText("修改");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btncancel.setText("取消");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btndelete.setText("删除");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnexit.setText("退出");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 869, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtsid)
                                    .addComponent(txtagent, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                    .addComponent(txtphone))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbappliction, 0, 130, Short.MAX_VALUE)
                                    .addComponent(txtsname)
                                    .addComponent(txtMphone)))
                            .addComponent(txtFaddress))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtcname)
                            .addComponent(txtcom_address)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnadd)
                        .addGap(18, 18, 18)
                        .addComponent(btnf5)
                        .addGap(18, 18, 18)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btncancel)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnexit)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtsid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtsname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtcname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtagent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(jcbappliction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(txtcom_address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(txtMphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtfax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtFaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(btnadd)
                    .addComponent(btnf5)
                    .addComponent(btnupdate)
                    .addComponent(btncancel)
                    .addComponent(btndelete)
                    .addComponent(btnexit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
         setVisible(false);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        String sid = this.txtsid.getText().trim();
        String sname = this.txtsname.getText().trim();
        String cname = this.txtcname.getText().trim();
        String agent = this.txtagent.getText().trim();
        String appli = this.jcbappliction.getSelectedItem().toString().trim();
        String caddress = this.txtcom_address.getText().trim();
        String phone = this.txtphone.getText().trim();
        String mphone=this.txtMphone.getText().trim();
        String fax=this.txtfax.getText().trim();
        String faddress=this.txtFaddress.getText().trim();
        if(StringUtile.validateNull(sid) == false){
            JOptionPane.showMessageDialog(this,"供应商编号不能为空");
            return;
        }
        if(StringUtile.validateNull(sname) == false){
            JOptionPane.showMessageDialog(this,"供应商简称不能为空");
            return;
        }
          if(StringUtile.validateDigit(sid) == false){
            JOptionPane.showMessageDialog(this, "供应商编号须为数字");
            return;
        }
        Supplier s = new Supplier(sid,sname,cname,agent,appli,caddress,phone,mphone,fax,faddress);
        if(isp.Thri_findBySupplier(s)){
            JOptionPane.showMessageDialog(this, "供应商已存在");
            btncancelActionPerformed( evt);
            return;
        
        }
        int result = isp.Thri_addSupplier(s);
         
          if(result != 0 ){
            JOptionPane.showMessageDialog(this, "添加成功");
            btnf5ActionPerformed( evt);
            btncancelActionPerformed(evt);
          }else{
              JOptionPane.showMessageDialog(this, "添加失败");
          }
    }//GEN-LAST:event_btnaddActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
     this.txtsid.setText("");
     this.txtsname.setText("");
     this.txtcname.setText("");
     this.txtagent.setText("");
     this.jcbappliction.setSelectedItem(" ");
     this.txtcom_address.setText("");
     this.txtphone.setText("");
     this.txtMphone.setText("");
     this.txtfax.setText("");
     this.txtFaddress.setText("");
      this.txtsid.setEnabled(true);
       this.txtsname.setEnabled(true);
     this.btnadd.setEnabled(true);//启用添加按钮
     this.btndelete.setEnabled(false);//禁用删除
     this.btnupdate.setEnabled(false);//禁用修改
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnf5ActionPerformed
        // TODO add your handling code here:
         List<Supplier> list =isp.Thri_getSipplier();
        // 获取表格中的行进行删除
        DefaultTableModel dtm =(DefaultTableModel) this.tblSupplier.getModel();
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);
        }
        for(Supplier s :list){
            Vector v = new Vector();
            v.add(s.getSupplierId());
            v.add(s.getSimpleName());
            v.add(s.getCompleteName());
            v.add(s.getAgent());
            v.add(s.getAppellation());
            v.add(s.getCompanyAddress());
            v.add(s.getPhone());
            v.add(s.getMobilePhone());
            v.add(s.getFax());
            v.add(s.getFactoryAddress());
            dtm.addRow(v);
        }
    }//GEN-LAST:event_btnf5ActionPerformed

    private void tblSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSupplierMouseClicked
        // TODO add your handling code here:
       this.txtsid.setEnabled(false);
       this.txtsname.setEnabled(false);
       int selectRow =  this.tblSupplier.getSelectedRow();
       txtsid.setText((String)this.tblSupplier.getValueAt(selectRow,0));
       txtsname.setText((String)this.tblSupplier.getValueAt(selectRow, 1));
       txtcname.setText((String)this.tblSupplier.getValueAt(selectRow,2));
       txtagent.setText((String)this.tblSupplier.getValueAt(selectRow,3));
       jcbappliction.setSelectedItem((String)this.tblSupplier.getValueAt(selectRow,4));
      txtcom_address.setText((String)this.tblSupplier.getValueAt(selectRow,5));
      txtphone.setText((String)this.tblSupplier.getValueAt(selectRow,6));
      txtMphone.setText((String)this.tblSupplier.getValueAt(selectRow,7));
      txtfax.setText((String)this.tblSupplier.getValueAt(selectRow,8));      
      txtFaddress.setText((String)this.tblSupplier.getValueAt(selectRow,9));
      
      this.btnadd.setEnabled(false);
      this.btnupdate.setEnabled(true);
      this.btndelete.setEnabled(true);
    }//GEN-LAST:event_tblSupplierMouseClicked

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
         String sid = this.txtsid.getText().trim();
        String sname = this.txtsname.getText().trim();
        String cname = this.txtcname.getText().trim();
        String agent = this.txtagent.getText().trim();
        String appli = this.jcbappliction.getSelectedItem().toString().trim();
        String caddress = this.txtcom_address.getText().trim();
        String phone = this.txtphone.getText().trim();
        String mphone=this.txtMphone.getText().trim();
        String fax=this.txtfax.getText().trim();
        String faddress=this.txtFaddress.getText().trim();
         Supplier s = new Supplier(sid,sname,cname,agent,appli,caddress,phone,mphone,fax,faddress);
        
        int result = isp.Thri_updateSupplier(s);
         
          if(result != 0 ){
              JOptionPane.showMessageDialog(this, "修改成功");
            btnf5ActionPerformed( evt);
            btncancelActionPerformed(evt);
          }else{
              JOptionPane.showMessageDialog(this, "修改失败");
          }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         String name = this.txtsname.getText();
        
        int result = isp.Thri_deleteSupplier(name);
        if(result >0){
            JOptionPane.showMessageDialog(this, "删除成功");
             btnf5ActionPerformed( evt);
            btncancelActionPerformed(evt); 
        }else{
            JOptionPane.showMessageDialog(this, "删除失败");
        }
    }//GEN-LAST:event_btndeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnf5;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbappliction;
    private javax.swing.JTable tblSupplier;
    private javax.swing.JTextField txtFaddress;
    private javax.swing.JTextField txtMphone;
    private javax.swing.JTextField txtagent;
    private javax.swing.JTextField txtcname;
    private javax.swing.JTextField txtcom_address;
    private javax.swing.JTextField txtfax;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtsid;
    private javax.swing.JTextField txtsname;
    // End of variables declaration//GEN-END:variables
}
