/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hp.View.JIF;

import com.hp.Dao.BuyBillIMPL;
import com.hp.Po.BuyBill;
import com.hp.Po.SaleBill;
import com.hp.Po.SupplierManagement;
import java.io.File;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Vector;
import javax.swing.AbstractButton;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dr.Thri
 */
public class SupplyTransactionManagement extends javax.swing.JInternalFrame {
    BuyBillIMPL bb = new BuyBillIMPL();
    

    /**
     * Creates new form SupplyTransactionManagement
     */
    public SupplyTransactionManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnTime = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        btnName = new javax.swing.JRadioButton();
        btnId = new javax.swing.JRadioButton();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnOut = new javax.swing.JButton();
        btnTchu = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("供应商交易管理");

        jLabel1.setText("第");

        btnTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "一", "二", "三", "四" }));

        jLabel2.setText("季度");

        buttonGroup1.add(btnName);
        btnName.setText("简称");

        buttonGroup1.add(btnId);
        btnId.setText("编号");

        btnSearch.setText("查询");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel3.setText("按供应商");

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "供应商编号", "供应商简称", "商品名称", "交易数量", "交易金额"
            }
        ));
        jScrollPane1.setViewportView(tblProduct);

        btnOut.setText("打印报表");
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        btnTchu.setText("关闭");
        btnTchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTchuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTime, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnName)
                        .addGap(18, 18, 18)
                        .addComponent(btnId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnOut)
                .addGap(59, 59, 59)
                .addComponent(btnTchu)
                .addGap(89, 89, 89))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnName)
                    .addComponent(btnId)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOut)
                    .addComponent(btnTchu))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String search=this.txtSearch.getText();
        int a=this.btnTime.getSelectedIndex();
        String b=this.btnTime.getItemAt(a);
        String enable="false";  
        Enumeration<AbstractButton> radioBtns=this.buttonGroup1.getElements();  
        while (radioBtns.hasMoreElements()) {  
        AbstractButton btn = radioBtns.nextElement();  
        if(btn.isSelected()){  
        enable=btn.getText();  
        break;  
            }  
        } 
        List<SupplierManagement> list= bb.getProduct(search,b,enable);       
        DefaultTableModel dtm =(DefaultTableModel) this.tblProduct.getModel();
        while(dtm.getRowCount() > 0){
            dtm.removeRow(0);       
        }
       for(SupplierManagement p :list){
            Vector v = new Vector();
            v.add(p.getSupplierId());
            v.add(p.getSimpleName());
            v.add(p.getBuyName());
            v.add(p.getBuyNum());
            v.add(p.getBuyPrice());
            dtm.addRow(v);
        } 
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        String search=this.txtSearch.getText();
        int a=this.btnTime.getSelectedIndex();
        String b=this.btnTime.getItemAt(a);
        String enable="false";  
        Enumeration<AbstractButton> radioBtns=this.buttonGroup1.getElements();  
        while (radioBtns.hasMoreElements()) {  
        AbstractButton btn = radioBtns.nextElement();  
        if(btn.isSelected()){  
        enable=btn.getText();  
        break;  
            }  
        } 
        List<SupplierManagement> pp = bb.getProduct(search,b,enable);   
        
        
        JFileChooser savefile = new JFileChooser();//文件选择对话框
        
        FileFilter filter = new FileNameExtensionFilter("Excel文件(*.xls)", "xls");
        savefile.addChoosableFileFilter(filter);//添加过滤器
        savefile.setFileFilter(filter);

        int flag = savefile.showSaveDialog(this);//打开文件选选择对话框
        File file = null;
        if (flag == JFileChooser.APPROVE_OPTION) {
        //如果点击了保存按钮
        file = savefile.getSelectedFile();//所选择的文件名（手写或选择）
        System.out.println("文件名：" + file.getAbsolutePath());
        String filename = file.getAbsolutePath();
        //截取文件扩展名（文件名长度后4位）
        String ftype = filename.substring(filename.length()-4);
        if(!ftype.equals(".xls")){
            //如果用户没有填写扩展名，自动添加扩展名.xls
            file = new File(filename+".xls");
        }
        //集合获取数据，输出到文件
        BuyBillIMPL.printSale(pp, file);
    }//GEN-LAST:event_btnOutActionPerformed
    }
    private void btnTchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTchuActionPerformed
        // TODO add your handling code here:
         dispose();
    }//GEN-LAST:event_btnTchuActionPerformed
   
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnId;
    private javax.swing.JRadioButton btnName;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTchu;
    private javax.swing.JComboBox<String> btnTime;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
