/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.hp.View;

import com.hp.Po.User;
import com.hp.View.JIF.ClientStuffManagement;
import com.hp.View.JIF.Login;
import com.hp.Util.FrameUtil2;
import com.hp.Util.LocationUtil;
import com.hp.View.JIF.*;
import java.beans.PropertyVetoException;
import java.util.Locale;
import javax.swing.JInternalFrame;

/**
 *
 * @author Dr.Thri
 */
public class MainFrame extends javax.swing.JFrame {
    User user2=null;
    /**
     * Creates new form NewJFrame
     */
    public MainFrame(User u) {
        initComponents();
       user2 = new User();
       user2=u;
        
        //顾客
        if(u.getPower()==10)
        {
            this.GoodsInfoManage.setEnabled(false);
            this.SupplierInfoManage.setEnabled(false);
            this.ClientInfoManage.setEnabled(false);
            this.btnGoodsInfoManage.setEnabled(false);
            this.StaffInfoManage.setEnabled(false);
            this.BuyIn.setEnabled(false);
            this.BuyDrop.setEnabled(false);
            this.SaleOut.setEnabled(false);
            this.SaleDrop.setEnabled(false);
            this.btnSaleOut.setEnabled(false); 
            this.btnStaffInfoManage.setEnabled(false);
            this.btnClientInfoManage.setEnabled(false);
            this.btnSupplierInfoManage.setEnabled(false);
            this.btnBuyDrop.setEnabled(false);
            this.btnBuyIn.setEnabled(false);
            this.btnSaleDrop.setEnabled(false);          
        }
        //销售管理员
        if(u.getPower()==9)
        {
            //this.SupplierInfoManage.setEnabled(false);
            this.StaffInfoManage.setEnabled(false);
            this.BuyQuery.setEnabled(false);
            this.BuyIn.setEnabled(false);
            this.BuyDrop.setEnabled(false);
            this.SupplierDealManage.setEnabled(false);
            this.StaticsBuy.setEnabled(false);
            this.btnStaffInfoManage.setEnabled(false);
            //this.btnClientInfoManage.setEnabled(false);
            //this.btnSupplierInfoManage.setEnabled(false);
            this.btnBuyDrop.setEnabled(false);
            this.btnBuyIn.setEnabled(false);
            //this.btnSupplierDealManage.setEnabled(false);
           // this.btnStaticsBuy.setEnabled(false);  
        }
        //员工
        if(u.getPower()==8)
        {
            this.StaffInfoManage.setEnabled(false);
        }
        //超级管理员
        if(u.getPower()==7)
        {
            
        }
       
       LocationUtil.setFullScreen(this);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jMenu1 = new javax.swing.JMenu();
        jToolBar1 = new javax.swing.JToolBar();
        btnStaffInfoManage = new javax.swing.JButton();
        btnClientInfoManage = new javax.swing.JButton();
        btnGoodsInfoManage = new javax.swing.JButton();
        btnSupplierInfoManage = new javax.swing.JButton();
        btnBuyIn = new javax.swing.JButton();
        btnBuyDrop = new javax.swing.JButton();
        btnSaleOut = new javax.swing.JButton();
        btnSaleDrop = new javax.swing.JButton();
        btnSupplierDealManage = new javax.swing.JButton();
        btnClientDealTip = new javax.swing.JButton();
        btnCountQuery = new javax.swing.JButton();
        btnStaticsBuy = new javax.swing.JButton();
        backGround1 = new com.hp.View.BackGround();
        show_Image1 = new com.hp.View.Show_Image();
        jMenuBar1 = new javax.swing.JMenuBar();
        BasicInfoManage = new javax.swing.JMenu();
        GoodsInfoManage = new javax.swing.JMenuItem();
        SupplierInfoManage = new javax.swing.JMenuItem();
        ClientInfoManage = new javax.swing.JMenuItem();
        StaffInfoManage = new javax.swing.JMenuItem();
        BuyManage = new javax.swing.JMenu();
        BuyQuery = new javax.swing.JMenuItem();
        BuyIn = new javax.swing.JMenuItem();
        BuyDrop = new javax.swing.JMenuItem();
        SaleManage = new javax.swing.JMenu();
        SaleSearch = new javax.swing.JMenuItem();
        SaleOut = new javax.swing.JMenuItem();
        SaleDrop = new javax.swing.JMenuItem();
        StaticsQuery = new javax.swing.JMenu();
        SupplierDealManage = new javax.swing.JMenuItem();
        ClientDealTip = new javax.swing.JMenuItem();
        CountQuery = new javax.swing.JMenuItem();
        StaticsBuy = new javax.swing.JMenuItem();

        jButton1.setText("jButton1");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnStaffInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salesmanmnu.gif"))); // NOI18N
        btnStaffInfoManage.setToolTipText("员工管理");
        btnStaffInfoManage.setFocusable(false);
        btnStaffInfoManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStaffInfoManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStaffInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaffInfoManageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStaffInfoManage);

        btnClientInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/customermnu.gif"))); // NOI18N
        btnClientInfoManage.setToolTipText("客户管理");
        btnClientInfoManage.setFocusable(false);
        btnClientInfoManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientInfoManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientInfoManageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientInfoManage);

        btnGoodsInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/productmnu.gif"))); // NOI18N
        btnGoodsInfoManage.setToolTipText("");
        btnGoodsInfoManage.setFocusable(false);
        btnGoodsInfoManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGoodsInfoManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnGoodsInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoodsInfoManageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGoodsInfoManage);

        btnSupplierInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/suppliernum.gif"))); // NOI18N
        btnSupplierInfoManage.setFocusable(false);
        btnSupplierInfoManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSupplierInfoManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSupplierInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierInfoManageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSupplierInfoManage);

        btnBuyIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/purchasemnu.gif"))); // NOI18N
        btnBuyIn.setFocusable(false);
        btnBuyIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuyIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuyIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyInActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuyIn);

        btnBuyDrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/retpurchasemnu.gif"))); // NOI18N
        btnBuyDrop.setFocusable(false);
        btnBuyDrop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBuyDrop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBuyDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyDropActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBuyDrop);

        btnSaleOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/sellmnu.gif"))); // NOI18N
        btnSaleOut.setFocusable(false);
        btnSaleOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaleOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaleOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleOutActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaleOut);

        btnSaleDrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/retsellmnu.gif"))); // NOI18N
        btnSaleDrop.setFocusable(false);
        btnSaleDrop.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSaleDrop.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSaleDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaleDropActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSaleDrop);

        btnSupplierDealManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/suppbusirecmnu.gif"))); // NOI18N
        btnSupplierDealManage.setFocusable(false);
        btnSupplierDealManage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSupplierDealManage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSupplierDealManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplierDealManageActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSupplierDealManage);

        btnClientDealTip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/custbusirecmnu.gif"))); // NOI18N
        btnClientDealTip.setFocusable(false);
        btnClientDealTip.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientDealTip.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientDealTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientDealTipActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientDealTip);

        btnCountQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/stockquerymnu.gif"))); // NOI18N
        btnCountQuery.setFocusable(false);
        btnCountQuery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCountQuery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCountQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCountQueryActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCountQuery);

        btnStaticsBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/purchasegathermnu.gif"))); // NOI18N
        btnStaticsBuy.setFocusable(false);
        btnStaticsBuy.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnStaticsBuy.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnStaticsBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStaticsBuyActionPerformed(evt);
            }
        });
        jToolBar1.add(btnStaticsBuy);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        backGround1.setLayer(show_Image1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout backGround1Layout = new javax.swing.GroupLayout(backGround1);
        backGround1.setLayout(backGround1Layout);
        backGround1Layout.setHorizontalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(show_Image1, javax.swing.GroupLayout.DEFAULT_SIZE, 855, Short.MAX_VALUE)
        );
        backGround1Layout.setVerticalGroup(
            backGround1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(show_Image1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
        );

        getContentPane().add(backGround1, java.awt.BorderLayout.CENTER);

        BasicInfoManage.setText("基本资料管理");

        GoodsInfoManage.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        GoodsInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/productmnu.gif"))); // NOI18N
        GoodsInfoManage.setText("商品管理");
        GoodsInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoodsInfoManageActionPerformed(evt);
            }
        });
        BasicInfoManage.add(GoodsInfoManage);

        SupplierInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/supplierframe.gif"))); // NOI18N
        SupplierInfoManage.setText("供应商管理");
        SupplierInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierInfoManageActionPerformed(evt);
            }
        });
        BasicInfoManage.add(SupplierInfoManage);

        ClientInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/customermnu.gif"))); // NOI18N
        ClientInfoManage.setText("客户管理");
        ClientInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientInfoManageActionPerformed(evt);
            }
        });
        BasicInfoManage.add(ClientInfoManage);

        StaffInfoManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/salesmanmnu.gif"))); // NOI18N
        StaffInfoManage.setText("员工管理");
        StaffInfoManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffInfoManageActionPerformed(evt);
            }
        });
        BasicInfoManage.add(StaffInfoManage);

        jMenuBar1.add(BasicInfoManage);

        BuyManage.setText("采购管理");

        BuyQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aboutframe.gif"))); // NOI18N
        BuyQuery.setText("采购查询");
        BuyQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyQueryActionPerformed(evt);
            }
        });
        BuyManage.add(BuyQuery);

        BuyIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/purchasemnu.gif"))); // NOI18N
        BuyIn.setText("采购入库");
        BuyIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyInActionPerformed(evt);
            }
        });
        BuyManage.add(BuyIn);

        BuyDrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/retpurchasemnu.gif"))); // NOI18N
        BuyDrop.setText("采购退货");
        BuyDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyDropActionPerformed(evt);
            }
        });
        BuyManage.add(BuyDrop);

        jMenuBar1.add(BuyManage);

        SaleManage.setText("销售管理");

        SaleSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/aboutnum.gif"))); // NOI18N
        SaleSearch.setText("销售查询");
        SaleSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleSearchActionPerformed(evt);
            }
        });
        SaleManage.add(SaleSearch);

        SaleOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/sellmnu.gif"))); // NOI18N
        SaleOut.setText("销售出库");
        SaleOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleOutActionPerformed(evt);
            }
        });
        SaleManage.add(SaleOut);

        SaleDrop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/retsellmnu.gif"))); // NOI18N
        SaleDrop.setText("销售退货");
        SaleDrop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaleDropActionPerformed(evt);
            }
        });
        SaleManage.add(SaleDrop);

        jMenuBar1.add(SaleManage);

        StaticsQuery.setText("统计查询");

        SupplierDealManage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/suppbusirecmnu.gif"))); // NOI18N
        SupplierDealManage.setText("供应商交易管理");
        SupplierDealManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SupplierDealManageActionPerformed(evt);
            }
        });
        StaticsQuery.add(SupplierDealManage);

        ClientDealTip.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/custbusirecmnu.gif"))); // NOI18N
        ClientDealTip.setText("客户历史交易记录");
        ClientDealTip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientDealTipActionPerformed(evt);
            }
        });
        StaticsQuery.add(ClientDealTip);

        CountQuery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/stockquerymnu.gif"))); // NOI18N
        CountQuery.setText("库存查询");
        CountQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountQueryActionPerformed(evt);
            }
        });
        StaticsQuery.add(CountQuery);

        StaticsBuy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/purchasegathermnu.gif"))); // NOI18N
        StaticsBuy.setText("采购统计");
        StaticsBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaticsBuyActionPerformed(evt);
            }
        });
        StaticsQuery.add(StaticsBuy);

        jMenuBar1.add(StaticsQuery);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GoodsInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoodsInfoManageActionPerformed
        // TODO add your handling code here:
    showFrame2(ClientStuffManagement.class);
    
    }//GEN-LAST:event_GoodsInfoManageActionPerformed

    private void SupplierInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierInfoManageActionPerformed
        // TODO add your handling code here:
        showFrame2(SupplyManagement.class);
    }//GEN-LAST:event_SupplierInfoManageActionPerformed

    private void ClientInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientInfoManageActionPerformed
        // TODO add your handling code here:
        showFrame2(CustomerManagement.class);
    }//GEN-LAST:event_ClientInfoManageActionPerformed

    private void StaffInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffInfoManageActionPerformed
        // TODO add your handling code here:
        showFrame2(EmployeeManagement.class);
    }//GEN-LAST:event_StaffInfoManageActionPerformed

    private void BuyQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyQueryActionPerformed
        // TODO add your handling code here:
        showFrame2(PurchaseSearch.class);
    }//GEN-LAST:event_BuyQueryActionPerformed

    private void BuyInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyInActionPerformed
        // TODO add your handling code here:
        showFrame2(PurchaseInWarehouse.class);
    }//GEN-LAST:event_BuyInActionPerformed

    private void BuyDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyDropActionPerformed
        // TODO add your handling code here:
        showFrame2(PurchaseReturns.class);
    }//GEN-LAST:event_BuyDropActionPerformed

    private void SaleSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleSearchActionPerformed
        // TODO add your handling code here:
        showFrame2(SaleSearch.class);
    }//GEN-LAST:event_SaleSearchActionPerformed

    private void SaleOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleOutActionPerformed
        // TODO add your handling code here:
        showFrame2(SellOutLibrary.class);
    }//GEN-LAST:event_SaleOutActionPerformed

    private void SaleDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaleDropActionPerformed
        // TODO add your handling code here:
        showFrame2(SaleReturn.class);
    }//GEN-LAST:event_SaleDropActionPerformed

    private void SupplierDealManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SupplierDealManageActionPerformed
        // TODO add your handling code here:
        showFrame2(SupplyTransactionManagement.class);
        
    }//GEN-LAST:event_SupplierDealManageActionPerformed

    private void ClientDealTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientDealTipActionPerformed
        // TODO add your handling code here:
       showFrame2(CustomerTransactions.class);
    }//GEN-LAST:event_ClientDealTipActionPerformed

    private void CountQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountQueryActionPerformed
        // TODO add your handling code here:
      showFrame2(InventoryInquiries.class);
    }//GEN-LAST:event_CountQueryActionPerformed

    private void StaticsBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaticsBuyActionPerformed
        // TODO add your handling code here:
       showFrame2(ProcurementStatistics.class);
    }//GEN-LAST:event_StaticsBuyActionPerformed

    private void btnStaffInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaffInfoManageActionPerformed
        // TODO add your handling code here:
        showFrame2(EmployeeManagement.class);
    }//GEN-LAST:event_btnStaffInfoManageActionPerformed

    private void btnClientInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientInfoManageActionPerformed
        // TODO add your handling code here:
        showFrame2(CustomerManagement.class);
    }//GEN-LAST:event_btnClientInfoManageActionPerformed

    private void btnSupplierInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierInfoManageActionPerformed
        // TODO add your handling code here:
         showFrame2(SupplyManagement.class);
    }//GEN-LAST:event_btnSupplierInfoManageActionPerformed

    private void btnGoodsInfoManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoodsInfoManageActionPerformed
        // TODO add your handling code here:
         showFrame2(ClientStuffManagement.class);
    }//GEN-LAST:event_btnGoodsInfoManageActionPerformed

    private void btnBuyInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyInActionPerformed
        // TODO add your handling code here:
        showFrame2(PurchaseInWarehouse.class);
    }//GEN-LAST:event_btnBuyInActionPerformed

    private void btnBuyDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyDropActionPerformed
        // TODO add your handling code here:
         showFrame2(PurchaseReturns.class);
    }//GEN-LAST:event_btnBuyDropActionPerformed

    private void btnSaleOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleOutActionPerformed
        // TODO add your handling code here:
        showFrame2(SellOutLibrary.class);
    }//GEN-LAST:event_btnSaleOutActionPerformed

    private void btnSaleDropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaleDropActionPerformed
        // TODO add your handling code here:
        showFrame2(SaleReturn.class);
    }//GEN-LAST:event_btnSaleDropActionPerformed

    private void btnSupplierDealManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplierDealManageActionPerformed
        // TODO add your handling code here:
         showFrame2(SupplyTransactionManagement.class);
    }//GEN-LAST:event_btnSupplierDealManageActionPerformed

    private void btnClientDealTipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientDealTipActionPerformed
        // TODO add your handling code here:
        showFrame2(CustomerTransactions.class);
    }//GEN-LAST:event_btnClientDealTipActionPerformed

    private void btnCountQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCountQueryActionPerformed
        // TODO add your handling code here:
          showFrame2(InventoryInquiries.class);
    }//GEN-LAST:event_btnCountQueryActionPerformed

    private void btnStaticsBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStaticsBuyActionPerformed
        // TODO add your handling code here:
         showFrame2(ProcurementStatistics.class);
    }//GEN-LAST:event_btnStaticsBuyActionPerformed
//显示内部窗体方法
    public void showFrame2(Class class1){
           try {
              
            //1 创建对象
            
            JInternalFrame inframe = FrameUtil2.buildFrame(class1);
          
            //2 添加到桌面面板
           this.backGround1.remove(inframe);
           this.backGround1.add(inframe);
            //3显示
            //设置窗体显示位置
           
            LocationUtil.setScreenCenter(inframe);
            inframe.setVisible(true);
            inframe.toFront();
            inframe.setSelected(true);
        } catch (PropertyVetoException ex) {
          ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BasicInfoManage;
    private javax.swing.JMenuItem BuyDrop;
    private javax.swing.JMenuItem BuyIn;
    private javax.swing.JMenu BuyManage;
    private javax.swing.JMenuItem BuyQuery;
    private javax.swing.JMenuItem ClientDealTip;
    private javax.swing.JMenuItem ClientInfoManage;
    private javax.swing.JMenuItem CountQuery;
    private javax.swing.JMenuItem GoodsInfoManage;
    private javax.swing.JMenuItem SaleDrop;
    private javax.swing.JMenu SaleManage;
    private javax.swing.JMenuItem SaleOut;
    private javax.swing.JMenuItem SaleSearch;
    private javax.swing.JMenuItem StaffInfoManage;
    private javax.swing.JMenuItem StaticsBuy;
    private javax.swing.JMenu StaticsQuery;
    private javax.swing.JMenuItem SupplierDealManage;
    private javax.swing.JMenuItem SupplierInfoManage;
    private com.hp.View.BackGround backGround1;
    private javax.swing.JButton btnBuyDrop;
    private javax.swing.JButton btnBuyIn;
    private javax.swing.JButton btnClientDealTip;
    private javax.swing.JButton btnClientInfoManage;
    private javax.swing.JButton btnCountQuery;
    private javax.swing.JButton btnGoodsInfoManage;
    private javax.swing.JButton btnSaleDrop;
    private javax.swing.JButton btnSaleOut;
    private javax.swing.JButton btnStaffInfoManage;
    private javax.swing.JButton btnStaticsBuy;
    private javax.swing.JButton btnSupplierDealManage;
    private javax.swing.JButton btnSupplierInfoManage;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JToolBar jToolBar1;
    private com.hp.View.Show_Image show_Image1;
    // End of variables declaration//GEN-END:variables
}
