/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hp.View;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author Administrator
 */
public class Show_Image extends javax.swing.JPanel {
   private Image img;
    /**
     * Creates new form NewJPanel
     */
    public Show_Image() {
     

        initComponents();
        //设置面板的背景图片，注意图片路径
         this.setImgURL(this.getClass().getResource("/imgs/elms.jpg"));
        
    }
        // 增加成员方法：
        public void setImgURL(URL imgURL){
           img = Toolkit.getDefaultToolkit().createImage(imgURL);
    }
    // 重写paintComponent方法
    public void paintComponent(Graphics g){        
        if(this.img == null) return;   
        g.drawImage(img, 0,0,this.getParent().getWidth(),this.getParent().getHeight(),this);         
    } 


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
